### ISSUE TITLE
Unexpected token =

### ISSUE THREAD

**Issue by binarykitchen** [lorenzofox3/zora#4]
To reproduce, `git clone https://github.com/binarykitchen/videomail-client/tree/feature/rollupjs` && `yarn install` && `yarn test`. Produces this output:

```
└─( 2 ) ❱❱❱ yarn test                                                                       1 ⏎  +2635 22:37 ❰─┘
yarn test v0.27.5
$ rollup -c env/test/rollup.config.js | tape-run
🚨   (regenerator plugin) Line 523: Unexpected token =
node_modules/zora/dist/zora.es.js

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: javascript required
    at Stream.<anonymous> (/home/michael-heuberger/code/videomail-client/node_modules/browser-run/index.js:35:34)
    at _end (/home/michael-heuberger/code/videomail-client/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/michael-heuberger/code/videomail-client/node_modules/through/index.js:74:5)
    at Stream.method [as end] (/home/michael-heuberger/code/videomail-client/node_modules/duplexer/index.js:47:39)
    at Stream.<anonymous> (/home/michael-heuberger/code/videomail-client/node_modules/throughout/index.js:7:25)
    at _end (/home/michael-heuberger/code/videomail-client/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/michael-heuberger/code/videomail-client/node_modules/through/index.js:74:5)
    at Stream.onend (internal/streams/legacy.js:44:10)
    at emitNone (events.js:110:20)
    at Stream.emit (events.js:207:7)
error Command failed with exit code 1.
```

Since it comes from `node_modules/zora/dist/zora.es.js` I guess I start reporting this here. Maybe you have any ideas/suggestions what this could be?

**Comment by lorenzofox3** [comment]
https://github.com/lorenzofox3/zora/blob/master/dist/zora.es.js#L523 it seems the environment you want to run your javascript does not know the default parameter introduced in the ecmascript2016  specifications. You probably need to transpile your code before
