### ISSUE TITLE
None of the tests are passing

### ISSUE THREAD

**Issue by TehShrike** [lorenzofox3/zora#42]
I cloned the repo to poke at an issue, installed, and ran the tests, and they all fail.

It appears that the tests always return an empty string right now.

Tested on `e1d8f5c` (the latest commit in the master branch as I write this issue).

Here's the output of the final test as an example:

```
# sample output indented: skip.js
not ok 28 should be equal
  ---
    operator: equal
    expected: |-
      'TAP version 13\nok 1 - hey hey\nok 2 - hey hey bis\n# Subtest: hello world\n    ok 1 - should be truthy\n    # Subtest: blah\n        1..0\n    ok 2 - blah # SKIP\n    # Subtest: for some reason\n        1..0\n    ok 3 - for some reason # SKIP\n    1..3\nok 3 - hello world # {TIME}\n# Subtest: failing text\n    1..0\nok 4 - failing text # SKIP\n1..4\n\n# ok\n# success: 3\n# skipped: 3\n# failure: 0\n'
    actual: |-
      ''
    at: Socket.cp.stdout.on (/Users/josh/code/zora/test/samples/index.js:37:15)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/Users/josh/code/zora/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/Users/josh/code/zora/node_modules/tape/lib/test.js:77:32)
          at Test.equal (/Users/josh/code/zora/node_modules/tape/lib/test.js:386:10)
          at Test.bound [as equal] (/Users/josh/code/zora/node_modules/tape/lib/test.js:77:32)
          at Socket.cp.stdout.on (/Users/josh/code/zora/test/samples/index.js:37:15)
          at Socket.emit (events.js:194:15)
          at endReadableNT (_stream_readable.js:1125:12)
          at process._tickCallback (internal/process/next_tick.js:63:19)
  ...

1..28
# tests 28
# pass  0
# fail  28
```

**Comment by lorenzofox3** [comment]
you need to build first ``npm run build`` I should update the npm scripts to make sure it is the case

**Comment by TehShrike** [comment]
ah, yeah, that feels like a broken test script.  I expect `npm it` to be the only thing necessary to run the test suite after cloning, and I expect to only need to run `npm t` after a code change in order to see if the test suite still passes after my change.
