### ISSUE TITLE
Output about a failed test not formattable

### ISSUE THREAD

**Issue by prantlf** [lorenzofox3/zora#82]
It appears, that the TAP formatters using `tap-out` for parsing fail with the output from `zora` in case of a test failure, because the stack trace is not formatted as expected. `faucet` works, `tap-dot` does not, for example.

Would it be possible to format the stack trace like `tape` does it? It would help especially the output of `tape-run`, where the stack trace is obviously malformed.

A test command:

    $ node test/node.test.js | ./node_modules/.bin/tap-dot

      ...x/Users/prantlf/Sources/github/janado/node_modules/.pnpm/tap-out@1.4.2/node_modules/tap-out/index.js:154
          .replace('(', '')
          ^

    TypeError: Cannot read property 'replace' of undefined
        at Parser._handleError (/Users/prantlf/Sources/github/janado/node_modules/.pnpm/tap-out@1.4.2/node_modules/tap-out/index.js:154:7)

The place in `tap-out` that fails:

    if (m[0] === 'stack') {
      this.writingErrorStackOutput = true;
      return;
    }

    var msg = trim((m[1] || '').replace(/['"]+/g, ''));

    if (m[0] === 'at') {
      // Example string: Object.async.eachSeries (/Users/scott/www/modules/nash/node_modules/async  /lib/async.js:145:20)

      msg = msg
      .split(' ')[1]
      .replace('(', '') // line 154 fails
      .replace(')', '');

An unformatted output from `zora` run with `node`:

    # an empty element
    not ok 4 - should be equivalent
      ---
        actual: "<div></div>"
        expected: "<div></di>"
        operator: "equal"
        at: " /Users/prantlf/Sources/github/janado/test/node.test.js:24:5"
      ...

An unformatted output from `tape` run with `node`:

    # an empty element
    not ok 4 should be strictly equal
      ---
        operator: equal
        expected: '<div></di>'
        actual:   '<div></div>'
        at: Test.<anonymous> (/Users/prantlf/Sources/github/janado/test/node.test.js:27:5)
        stack: |-
          Error: should be strictly equal
              at Test.assert [as _assert] (/Users/prantlf/Sources/github/janado/node_modules/.pnpm/tape@5.2.0/node_modules/tape/lib/test.js:310:54)
              at Test.bound [as _assert] (/Users/prantlf/Sources/github/janado/node_modules/.pnpm/tape@5.2.0/node_modules/tape/lib/test.js:91:32)
              at Test.strictEqual (/Users/prantlf/Sources/github/janado/node_modules/.pnpm/tape@5.2.0/node_modules/tape/lib/test.js:474:10)
              at Test.bound [as equal] (/Users/prantlf/Sources/github/janado/node_modules/.pnpm/tape@5.2.0/node_modules/tape/lib/test.js:91:32)
              at Test.<anonymous> (/Users/prantlf/Sources/github/janado/test/node.test.js:27:5)
              at Test.bound [as _cb] (/Users/prantlf/Sources/github/janado/node_modules/.pnpm/tape@5.2.0/node_modules/tape/lib/test.js:91:32)
              at Test.run (/Users/prantlf/Sources/github/janado/node_modules/.pnpm/tape@5.2.0/node_modules/tape/lib/test.js:108:31)
              at Test.bound [as run] (/Users/prantlf/Sources/github/janado/node_modules/.pnpm/tape@5.2.0/node_modules/tape/lib/test.js:91:32)
              at Immediate.next [as _onImmediate] (/Users/prantlf/Sources/github/janado/node_modules/.pnpm/tape@5.2.0/node_modules/tape/lib/results.js:89:19)
              at processImmediate (internal/timers.js:461:21)
      ...

An unformatted output from `zora` run with `tape-run`:

    # an empty element
    not ok 2 - should be equivalent
      ---
        actual: "<div></div>"
        expected: "<div></di>"
        operator: "equal"
        at: " http://localhost:56765/bundle.js:1085:5"
      ...

An unformatted output from `tape` run with `tape-run`:

    # an empty element
    not ok 2 should be strictly equal
      ---
        operator: equal
        expected: '<div></di>'
        actual:   '<div></div>'
        stack: |-
          Error: should be strictly equal
              at Test.assert [as _assert] (http://localhost:57528/bundle.js:10760:54)
              at Test.bound [as _assert] (http://localhost:57528/bundle.js:10541:32)
              at Test.strictEqual (http://localhost:57528/bundle.js:10924:10)
              at Test.bound (http://localhost:57528/bundle.js:10541:32)
              at Test.<anonymous> (http://localhost:57528/bundle.js:11613:5)
              at Test.bound [as _cb] (http://localhost:57528/bundle.js:10541:32)
              at Test.run (http://localhost:57528/bundle.js:10558:31)
              at Test.bound [as run] (http://localhost:57528/bundle.js:10541:32)
              at next (http://localhost:57528/bundle.js:10315:19)
              at onNextTick (http://localhost:57528/bundle.js:11386:12)
      ...

**Comment by lorenzofox3** [comment]
Thanks for the report. 

I believe the problem comes from ``tap-out`` itself

>  .split(' ')[1]

It is somehow a weak implementation making assumption on a field which is not specified by the TAP specification and I suggest you to open a PR on their side. 

The point is that ``tape`` is not able to locate the user code and needs to use the whole stack trace. Whereas zora finds directly the user code trimming all the package internals calls. 

We could add some lines of the stacktrace to avoid the breakage but that would be a hack adding unnecessary noise, only to support a specific package whose implementation is a bit tedious.

Also I noticed your sample uses an old version of ``tap-out``. 

You could use [tap-parser](https://www.npmjs.com/package/tap-parser) which seems more robust and popular. 

Alternatively you can use zora's protocole to quickly build a custom reporter, that is pretty straightforward nowadays with async iterators.
